import type { Article } from '../types/article'

export const SAMPLE_ARTICLES: Article[] = [
  {
    id: '1',
    source: 'Platformer',
    author: 'Casey Newton',
    date: 'Mar 28, 2026',
    receivedAt: '2026-03-28T14:00:00Z',
    readTime: '8 min',
    category: 'Tech',
    title: 'The AI Agent Wars Have Officially Begun',
    summary: 'Every major tech company is now racing to build autonomous AI agents, and the battle lines are being drawn in ways that will reshape the entire industry.',
    content: [
      'For more than a decade, Apple and Google have maintained an iron grip on mobile software distribution. The App Store and Google Play became the default gateways through which billions of people access the internet, and the 30 percent commission that both companies charge developers became one of the most reliable revenue streams in the history of technology.',
      'That era is coming to an end. This week, the European Commission announced its latest enforcement action under the Digital Markets Act, ordering both companies to allow third-party app stores on their platforms with no restrictions on payment processing. The fines for noncompliance would start at 10 percent of global revenue — a figure that, for Apple, would exceed $39 billion.',
      'The timing is notable. In the United States, a bipartisan coalition in the Senate has introduced the Open App Markets Act, which would impose similar requirements domestically. And in Japan, new legislation taking effect next month will require Apple to permit sideloading for the first time.',
      'Apple has responded with what might be charitably described as malicious compliance. In the EU, developers can now use alternative payment systems, but Apple has introduced a new "Core Technology Fee" that charges 50 cents per app install after the first million. For free apps with large user bases, this could actually cost more than the old commission.',
      'Google has taken a different approach, quietly settling with major developers like Spotify and Epic Games while maintaining its commission structure for smaller players. The strategy seems designed to defuse the loudest critics while preserving the bulk of its revenue.',
      'What neither company seems willing to acknowledge is that the fundamental model is broken. The idea that a platform owner should take a significant cut of every transaction that happens on its hardware made sense in 2008, when the App Store was a novel distribution mechanism. In 2026, it looks more like a toll booth on a public road.',
      'The next twelve months will likely determine whether the app store model survives in its current form or transforms into something more closely resembling the open web. For developers, the stakes could not be higher.'
    ],
    gmailMessageId: '',
    heroColor: '#1a1a2e',
    accentColor: '#e94560',
  },
  {
    id: '2',
    source: 'Money Stuff',
    author: 'Matt Levine',
    date: 'Mar 27, 2026',
    receivedAt: '2026-03-27T18:30:00Z',
    readTime: '11 min',
    category: 'Finance',
    title: 'The Tokenized Treasury Market Is Getting Weird',
    summary: 'Wall Street is tokenizing U.S. Treasuries on blockchains at a rapid clip, and the resulting market structure is stranger than anyone predicted.',
    content: [
      'There is a thing that happens on Wall Street every fifteen years or so where someone invents a new way to package risk, everyone gets very excited about it, and then it blows up. We are currently in the "everyone gets very excited" phase of the latest cycle, and the instruments in question are synthetic collateralized debt obligations referencing portfolios of private credit loans.',
      'If that sentence made you nervous, congratulations, you have a functioning memory. Synthetic CDOs were, of course, central to the 2008 financial crisis. The basic idea is that instead of buying actual loans and pooling them together, you use credit default swaps to create a synthetic exposure to a reference portfolio. This lets you create leveraged bets on credit risk without anyone having to actually lend money to anyone.',
      'The new twist is that the reference portfolios are not mortgage-backed securities but private credit loans — the direct lending that has exploded over the past five years as banks retreated from middle-market lending. Private credit funds now hold roughly $1.7 trillion in assets, and the loans they make are generally illiquid, hard to value, and lightly regulated.',
      'So naturally, Wall Street would like to create synthetic leveraged exposure to these loans. Goldman Sachs, JPMorgan, and Citigroup have all launched synthetic CDO desks focused on private credit in the past year. The total notional outstanding is estimated at around $200 billion, though nobody really knows because these are bilateral over-the-counter transactions.',
      'The bull case is straightforward: private credit loans have historically low default rates, the synthetic structure allows investors to choose their preferred level of risk, and the spreads are attractive relative to public credit markets. A senior tranche of a synthetic CDO referencing a diversified pool of private credit loans might yield 200 basis points over SOFR, which is genuinely appealing in the current rate environment.',
      'The bear case is that we are creating leveraged, opaque exposure to assets that are themselves illiquid and opaque, and that the historical default data for private credit is drawn from a period of unusually low interest rates and easy financial conditions. The private credit boom coincided almost exactly with the era of zero interest rates, which is not a great sample for stress-testing.',
      'I do not want to be alarmist about this. The volumes are still modest relative to the overall market, the investors are mostly sophisticated institutions, and the regulatory framework is meaningfully better than it was in 2007. But I also think it is worth noting, as a matter of financial history, that the phrase "this time is different" has a remarkably poor track record.'
    ],
    gmailMessageId: '',
    heroColor: '#0a0a0a',
    accentColor: '#00d4aa',
  },
  {
    id: '3',
    source: 'Stratechery',
    author: 'Ben Thompson',
    date: 'Mar 26, 2026',
    receivedAt: '2026-03-26T12:00:00Z',
    readTime: '10 min',
    category: 'Strategy',
    title: 'The End of the Aggregation Era',
    summary: 'AI assistants are quietly dismantling the aggregator business model that defined the last decade of tech, and most incumbents have no idea how to respond.',
    content: [
      'The concept I introduced in Aggregation Theory — that the internet would create winner-take-all dynamics by enabling platforms to aggregate demand at zero marginal cost — has held up remarkably well over the past decade. Google aggregated search queries, Facebook aggregated social connections, Amazon aggregated purchase intent, and all three became among the most valuable companies in history.',
      'I now believe we are entering a new era that will systematically dismantle the aggregator advantage. The catalyst is the maturation of AI assistants that sit between users and the services they consume. When a user asks an AI assistant to find the best restaurant nearby, book a flight, or research a purchase, the assistant becomes the new aggregation point — and the old aggregators become just another supplier.',
      'This is already happening in search. Google\u2019s search revenue growth has decelerated for four consecutive quarters, and the company\u2019s own AI Overview feature is cannibalizing traditional search results. But the more significant threat comes from standalone AI assistants that bypass Google entirely. When someone asks Claude or ChatGPT a question, there is no search results page, no ads, no ten blue links.',
      'The implications for the advertising model are profound. Aggregators monetize by selling access to aggregated demand — they sit between users and suppliers and charge suppliers for the privilege of being discovered. But if AI assistants are making the discovery decisions, the value shifts to whoever controls the assistant, not whoever controls the traditional aggregation point.',
      'The incumbents are not blind to this threat. Google is integrating Gemini into every product. Meta is building AI personas. Amazon is rebuilding Alexa around large language models. But each of these efforts faces a fundamental tension: the AI assistant model is inherently at odds with the advertising model that funds these companies.',
      'An AI assistant that genuinely serves the user\u2019s interests would never recommend a restaurant because it paid for placement. It would recommend the best restaurant, full stop. This is incompatible with the business model that generates the majority of revenue for Google and Meta.'
    ],
    gmailMessageId: '',
    heroColor: '#16213e',
    accentColor: '#f8b500',
  },
  {
    id: '4',
    source: 'Garbage Day',
    author: 'Ryan Broderick',
    date: 'Mar 25, 2026',
    receivedAt: '2026-03-25T16:00:00Z',
    readTime: '6 min',
    category: 'Culture',
    title: 'The Vibe Shift Already Happened',
    summary: 'Everyone spent years predicting the next cultural vibe shift without noticing it already arrived — and it looks nothing like anyone expected.',
    content: [
      'For the past three years, media people have been breathlessly predicting an imminent "vibe shift" — a wholesale transformation in internet culture that would sweep away the existing aesthetic and replace it with something new. The discourse around this has been exhausting, and I am here to tell you that the vibe shift already happened while everyone was busy writing trend pieces about it.',
      'The new vibe is: there is no vibe. Or more precisely, the monoculture has fragmented so completely that the concept of a dominant cultural mode no longer applies. There is no single aesthetic, no universal reference point, no shared internet experience that connects more than a tiny fraction of the population. We are all living in our own algorithmic realities, and the idea that a "vibe shift" could propagate across the entire culture is itself a relic of a more connected era.',
      'You can see this most clearly on TikTok, which is supposedly the vanguard of internet culture. Open TikTok on five different phones and you will see five completely different apps. The algorithm has become so precise at identifying individual taste that there is essentially no shared experience left. My TikTok is cooking videos and obscure history. Yours might be gym content and tech reviews. Neither of us has any idea what the other is watching.',
      'This has profound implications for anyone who makes a living interpreting culture — journalists, marketers, trend forecasters, and, yes, newsletter writers. The tools we developed for understanding mass culture simply do not work in a post-mass-culture world. You cannot identify a trend when every person is experiencing a different version of the internet.',
      'The irony is that this fragmentation was supposed to be the original promise of the internet: a million niche communities, each pursuing its own interests, free from the homogenizing force of mass media. We got exactly what we asked for. It just turns out that a world without shared cultural reference points is a little lonely.'
    ],
    gmailMessageId: '',
    heroColor: '#2d1b4e',
    accentColor: '#ff6b9d',
  },
  {
    id: '5',
    source: 'Slow Boring',
    author: 'Matthew Yglesias',
    date: 'Mar 24, 2026',
    receivedAt: '2026-03-24T13:00:00Z',
    readTime: '9 min',
    category: 'Policy',
    title: 'The Housing Theory of Everything Is Winning',
    summary: 'After years of advocacy, the YIMBY movement is finally seeing real legislative victories — and the economic data is starting to prove them right.',
    content: [
      'I have been writing about housing policy for long enough that I remember when "just build more housing" was considered a fringe position. The mainstream view, shared by most progressive advocacy organizations and a good chunk of the economics profession, was that new market-rate construction would not help affordability because developers only build luxury units. This view was wrong, and the evidence that it was wrong has become overwhelming.',
      'In the past year alone, three states — California, Washington, and Colorado — have passed comprehensive zoning reform legislation that effectively eliminates single-family-only zoning in urban areas. A dozen cities have adopted by-right permitting for multifamily construction near transit. And the results are starting to show up in the data.',
      'Austin, Texas, which reformed its land use rules in 2023, has seen rents decline by 12 percent in real terms over the past two years. Minneapolis, which eliminated single-family zoning in 2018, has maintained essentially flat rents while comparable cities saw increases of 15 to 20 percent. And in the most dramatic example, Tokyo — which has had permissive zoning for decades — remains one of the most affordable major cities in the developed world.',
      'The mechanism is not complicated. When you allow more housing to be built, more housing gets built. When more housing gets built, there is less competition for existing units. When there is less competition for existing units, prices moderate. This is the same supply-and-demand logic that applies to literally every other good in the economy, and it is gratifying to see it finally being applied to the single largest expenditure in most household budgets.',
      'The political coalition behind these reforms is genuinely novel. YIMBY groups have assembled alliances that cross traditional partisan lines: free-market conservatives who oppose regulatory barriers, progressives who care about affordability and displacement, environmentalists who want denser development near transit, and a growing number of young people who simply cannot afford to live in the cities where they work.',
      'There are legitimate concerns about gentrification and displacement that new construction alone will not solve. Low-income tenants need direct subsidies and strong tenant protections regardless of how much market-rate construction happens. But the evidence is now clear that restricting supply does not protect vulnerable communities — it just makes everyone poorer while enriching existing property owners.'
    ],
    gmailMessageId: '',
    heroColor: '#1b2d1b',
    accentColor: '#7fcd91',
  },
]
